global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8083']
        labels:
          application: 'Product Service'

  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8081']
        labels:
          application: 'Order Service'

  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8084']
        labels:
          application: 'Notification Service'

  - job_name: 'inventory_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8082']
        labels:
          application: 'Inventory Service'

  - job_name: 'api_gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8181' ]
        labels:
          application: 'API Gateway'

  - job_name: 'discovery_server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'discovery-server:8761' ]
        labels:
          application: 'Discovery Server'